# Generated by Django 4.2.6 on 2023-10-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
