# Generated by Django 4.2.6 on 2023-10-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isImportant',
            new_name='is_important',
        ),
    ]
