# Generated by Django 4.2.6 on 2023-10-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_isimportant_task_is_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datecompleted',
            new_name='date_completed',
        ),
    ]
